[FIX] UN-1068 Removing unused filetypes
Zipstack/unstract pull request #218
Opened 2024-04-01 15:10 UTC by harini-venkataraman

## What
Removing unsupported filetypes for I/O Connectors from the list.

## Why
Redundant filetypes mentioned in the list

## How
Removing the list from the JSON Schema

## Database Migrations
Not applicable.

## Env Config
Not applicable.

## Screenshots
![image](https://github.com/Zipstack/unstract/assets/115449948/0989e82e-6aec-4cd9-b5e9-5c95a59bfbe0)

## Checklist

I have read and understood the [Contribution Guidelines]().

2024-04-01 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zipstack/unstract?pullRequest=218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zipstack/unstract?pullRequest=218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zipstack/unstract?pullRequest=218) it.</sub>

2024-04-04 17:29 UTC, nehabagdia approved these changes

2024-04-04 17:29 UTC, nehabagdia commented on backend/workflow_manager/endpoint/static/src/file.json
> +
Nit: Please remove this extra line.

2024-04-05 04:39 UTC, tahierhussain approved these changes
LGTM

2024-04-06 04:02 UTC, chandrasekharan-zipstack requested changes
@harini-venkataraman please check [this validation](https://github.com/Zipstack/unstract/blob/afa50665be69fcf0398c8d29086b3b38ac7b8249/backend/workflow_manager/endpoint/source.py#L112-L118) and remove the unused file types from this as well

2024-04-16 10:46 UTC, muhammad-ali-e commented
@harini-venkataraman @chandrasekharan-zipstack @nehabagdia @tahierhussain 
 Isn't this validation based on various tools? Some tools support images, some support PDFs, and some both, right? So, why do we need to remove it from here?
 
 @hari-kuriakose

2024-04-17 07:15 UTC, harini-venkataraman commented
> @harini-venkataraman @chandrasekharan-zipstack @nehabagdia @tahierhussain Isn't this validation based on various tools? Some tools support images, some support PDFs, and some both, right? So, why do we need to remove it from here?
> 
> @hari-kuriakose

@muhammad-ali-e Word Document & Open office document, which we dont currently support are listed and this PR removes those. We have removed only those file types from validations and constants. PDF, word and images are retained.

2024-04-17 07:19 UTC, chandrasekharan-zipstack approved these changes
LGTM, do assess if we persist this data and if we might require migrations for it. I doubt if anyone might have set any of these options but its always good to be sure

2024-04-17 08:01 UTC, harini-venkataraman commented
> LGTM, do assess if we persist this data and if we might require migrations for it. I doubt if anyone might have set any of these options but its always good to be sure

@chandrasekharan-zipstack Currently we don`t persist filetype in database. Validation is done in tools for allowed filetypes apart from the files changed here - [Ref.](https://github.com/Zipstack/unstract-sdk/blob/c46fdc075e5e752b659599b6d92b5e0367265c1b/src/unstract/sdk/tool/validator.py#L200) While a new tool is developed we must ensure that non supported types are not used.

2024-04-17 08:04 UTC, merged