fix:add flake8/black on precommit hook
Zipstack/unstract pull request #233
Opened 2024-04-04 07:13 UTC by kirtimanmishrazipstack

## What

- Add flake8 on pre-commit hook

## Why

- it was commented on this repo

## How

- Added on `pre-commit-config.yaml`

## Database Migrations

- N/A

## Env Config

- N/A

## Relevant Docs

-

## Related Issues or PRs

-

## Dependencies Versions

-

## Notes on Testing

-

## Screenshots

## Checklist

I have read and understood the [Contribution Guidelines]().

2024-04-04 07:20 UTC, ritwik-g requested changes
@kirtimanmishrazipstack please change max length in black as well

2024-04-04 07:26 UTC, kirtimanmishrazipstack commented
> @kirtimanmishrazipstack please change max length in black as well

done @ritwik-g

2024-04-04 07:27 UTC, ritwik-g approved these changes

2024-04-04 08:03 UTC, chandrasekharan-zipstack requested changes
Please update pyproject.toml as well and re-run `pre-commit run --all-files`

2024-04-05 06:31 UTC, kirtimanmishrazipstack commented on .pre-commit-config.yaml
> +        args: [--config=pyproject.toml, -l 88]
done @chandrasekharan-zipstack

2024-04-05 06:51 UTC, chandrasekharan-zipstack approved these changes
LGTM

2024-04-15 09:33 UTC, closed without merging