fix: Enhanced WF logs and other minor fixes
Zipstack/unstract pull request #627
Opened 2024-08-27 11:24 UTC by chandrasekharan-zipstack

## What

- Enriched WF logs to display matched file patterns and the files
- Updated pipeline field `scheduled` to be set only when the cron string is set

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

- No

## Screenshots
![image](https://github.com/user-attachments/assets/493298fd-c195-4ffd-8427-4cbdba796fe2)

## Checklist

I have read and understood the [Contribution Guidelines]().

2024-08-27 11:58 UTC, muhammad-ali-e approved these changes
LGTM
Left one minor comment to remove a return statement

2024-08-27 11:58 UTC, muhammad-ali-e commented on backend/workflow_manager/endpoint/source.py
> +        return
remove this `return`

2024-08-27 16:57 UTC, harini-venkataraman approved these changes
LGTM

2024-08-27 19:44 UTC, Deepak-Kesavan requested changes

2024-08-27 19:44 UTC, Deepak-Kesavan commented on backend/workflow_manager/workflow/workflow_helper.py
>              except Exception as error:
@chandrasekharan-zipstack Can we change error as e here? It is confusing because same variable name is declared above

2024-08-27 19:48 UTC, Deepak-Kesavan commented
@chandrasekharan-zipstack Noticed that there is a new sonar issue introduced in this PR. Please take a look into it.

2024-08-28 04:56 UTC, vishnuszipstack approved these changes

2024-08-28 06:42 UTC, Deepak-Kesavan approved these changes

2024-08-28 12:28 UTC, merged