FIX: Refactored the DisplayPromptResult Component
Zipstack/unstract pull request #711
Opened 2024-09-18 18:29 UTC by tahierhussain

## What

Refactored the `DisplayPromptResult` component to handle the case where the output is empty.

## Why

The `DisplayPromptResult` component needed to be used in multiple places, along with the block of code that handles rendering when the output is undefined or empty.

## How

To avoid code duplication, I moved the block of code that displays when the output is empty or undefined inside the `DisplayPromptResult` component.

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

No. This PR consists of minor refactoring of the frontend components, so the chances of it breaking other features are minimal.

## Database Migrations

NA 

## Env Config

NA

## Relevant Docs

NA

## Related Issues or PRs

NA

## Dependencies Versions

NA

## Notes on Testing

NA

## Screenshots
![image](https://github.com/user-attachments/assets/0ac0b71c-1b1d-47be-afd7-0764a6d68862)

## Checklist

I have read and understood the [Contribution Guidelines]().

2024-09-18 18:53 UTC, jagadeeswaran-zipstack requested changes

2024-09-18 18:53 UTC, jagadeeswaran-zipstack commented on frontend/src/components/custom-tools/prompt-card/DisplayPromptResult.jsx
> +          <InfoCircleFilled style={{ color: "#F0AD4E" }} />
Inline style can be moved into css.

2024-09-18 21:40 UTC, Toughski commented on frontend/src/components/custom-tools/prompt-card/DisplayPromptResult.jsx
> +          <InfoCircleFilled style={{ color: "#F0AD4E" }} />
REFUND CYBER

2024-09-19 05:08 UTC, jagadeeswaran-zipstack approved these changes

2024-09-19 05:22 UTC, Deepak-Kesavan approved these changes

2024-09-19 05:36 UTC, merged