Multitenancy v2 changes for prompt studio apps - Prompt studio core, Registry
Zipstack/unstract pull request #720
Opened 2024-09-20 12:30 UTC by harini-venkataraman

## What
Multitenancy v2 changes for Prompt studio, Prompt studio core and Prompt studio registry.

...

## Why
Performance improvements.
...

## How

...

## Can this PR break any existing features. If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)
No, the code is not referred. 
...

## Database Migrations

- 

## Env Config

- 

## Relevant Docs

-

## Related Issues or PRs
https://github.com/Zipstack/unstract/pull/555/
https://github.com/Zipstack/unstract/pull/503/
https://github.com/Zipstack/unstract/pull/391
https://github.com/Zipstack/unstract/pull/564

-

## Dependencies Versions

-

## Notes on Testing
Untested code. Need to add migration files and test with migration.
-

## Screenshots

## Checklist

I have read and understood the [Contribution Guidelines]().

2024-09-24 04:05 UTC, muhammad-ali-e requested changes

2024-09-24 04:05 UTC, muhammad-ali-e commented on backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
> +from prompt_studio.prompt_profile_manager.models import ProfileManager
We need it from V2 instaed of V1

2024-09-24 04:05 UTC, muhammad-ali-e commented on backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
> +from prompt_studio.prompt_studio_document_manager.models import DocumentManager
models should import from V2

2024-09-24 04:05 UTC, muhammad-ali-e commented on backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
> +from prompt_studio.prompt_studio_index_manager.prompt_studio_index_helper import (  # noqa: E501
Why it changed to V1?

2024-09-25 07:00 UTC, muhammad-ali-e commented on backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
> +from prompt_studio.prompt_profile_manager.models import ProfileManager
updated

2024-09-25 07:00 UTC, muhammad-ali-e commented on backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
> +from prompt_studio.prompt_studio_document_manager.models import DocumentManager
updated

2024-09-25 07:00 UTC, muhammad-ali-e commented on backend/prompt_studio/prompt_studio_core_v2/prompt_studio_helper.py
> +from prompt_studio.prompt_studio_index_manager.prompt_studio_index_helper import (  # noqa: E501
updated

2024-09-25 07:17 UTC, hari-kuriakose commented
Duplication will be handled when we remove v1 later.

2024-09-25 07:17 UTC, merged

2024-09-25 07:21 UTC, hari-kuriakose commented on backend/prompt_studio/prompt_studio_v2/models.py
> +        on_delete=models.SET_NULL,
@harini-venkataraman Not sure if this is intended.

2024-09-25 07:22 UTC, hari-kuriakose reviewed
@harini-venkataraman Models look good overall.

Added a comment though.